baseURL = '/'
languageCode = 'en-us'
contentDir = 'content'
enableEmoji = true
title = 'CyberWatchDoug Projects'

[module]
    [module.hugoVersion]
        extended = true
        min = "0.100.0"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

#[menu]
    # [[menu.primary]]
    #     name  = "Docs"
    #     url = "docs/"
    #     identifier = "docs"
    #     weight = 10

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

# [[menu.primary]]
#     name  = "Community"
#     url = "https://github.com/colinwilson/lotusdocs/discussions"
#     identifier = "community"
#     weight = 30